### ISSUE TITLE
Public API for connect_adjacent_blocks

### ISSUE THREAD

**Issue by vlad-ivanov-name** [stfwi/srecord-cc#1]
Hello, 

thank you for sharing this library, it's really useful. Do you think it would make sense to have API for connect_adjacent_blocks()? It would simplify block handling for some use cases

**Comment by stfwi** [comment]
Hi, (I somehow managed to unwatch my own repository and did not get a notification!). 
Let me double check this, if I remember correctly that should be implicit when getting a range. I'll double check this weekend.

**Comment by stfwi** [comment]
Check if the `static block_type connect(block_container_type&& blocks, value_type fill_value)` method helps you in your case, this one also takes care of values that have to be used to fill gaps between the blocks.
I also have a concept implementation for nonstrict parsing, but this is not completely tested yet (and actually only needed for very strange srec composers, like the for the SDCC - this one mixes S1,2,3 in one file etc).

**Comment by stfwi** [comment]
Just saw you forked and fixed the issue already, so I close this one and will integrate the public API method in my local current dev testing tree. Cheers -
