### ISSUE TITLE
Problem in validate() when the file end is 0xFFFFFFFF

### ISSUE THREAD

**Issue by hansu** [stfwi/srecord-cc#2]
If one got a line like 
```S309FFFFFFFC0200E0FF1C```  
the end of the last block is shown as 0x0.
Changing  
```c
 typedef unsigned long address_type;
```
into
```c
  typedef unsigned long long address_type;
```
leaded to the errormessage "e_validate_record_type_to_small". (occur in srecord.hh, line 910):
```c
     if((type_ < 1) || (type_ > 3)) {
        return error(e_validate_record_type_to_small);
      }
```
But that is quite a valid data record even it is close to the edge.

**Comment by hansu** [comment]
Adding       `adr &= ~0x100000000;` solves the problem, but you may have a better, more clean solution.
```c
  bool validate(bool strict=true)
  {
    if(!good()) return false;

    // Check/set address type
    {
      unsigned type = 1;
      address_type adr = 0;
      for(block_type& block: blocks_) {
        adr |= block.eadr(); // -1 ? --> no
      }
      adr &= ~0x100000000; // <<<<<<<<<< here
      for(adr >>= 16; adr; adr >>= 8) ++type;
      if(type_ == type_undefined) {
        type_ = (record_type_type)type;
      } else if(type_ < type) {
        if(strict) {
          return error(e_validate_record_type_to_small);
        } else {
          type_ = record_type_type(type);
        }
      }
    }
```

**Comment by stfwi** [comment]
Hi Hans, I'll have a look at this at the weekend. My first guess is that `adr >>= 16` makes an arithmetic shift with your compiler. That would not fill zeros from the left, but ones if the sign bit is set. Could be that therefore `16u` has to be set.
Have to admit when writing this class quite a few years ago I did not take controller 4GB FLASH sizes - reaching to the end of the S-Record range - into account. As `eadr()` is inclusive, `0xffffffff` is basically still fine with `uint32_t`, so `ulonglong` should not be needed here. Cheers, -

**Comment by hansu** [comment]
Hi!
Thanks your you quick reply and of course also for providing your code!
Yes you are right an uint32_t should theoretically be large enough. 
I just figured out that your definition of the end address maybe is the problem. Because the end address is the address of the beginning of an eventually new byte.
In that case the last byte address is 0xFFFFFFFF but the following would be 0x100000000. And that exceeds the range of an uint32_t.
So block.eadr() returns a zero in case of end_address == 0x100000000

Parsing end_address as start_address + bin.size() -1 would also solve the main problem of this issue.
And a much better workaroud would be to use the `-1` like in your comment.
```c
   for(block_type& block: blocks_) {
        adr |= block.eadr()-1; // -1 ? --> no
      }
```

**Comment by stfwi** [comment]
Hi, thanks for digging into that. I'll have to double check the complete loading/parsing code for an, too. What we see here might be a side effect of an earlier u32 overrun.

**Comment by stfwi** [comment]
Bumped the `address_type` to `u64` and applied the old-school-approach with mask checking in `validate()`, that circumvents potential `ASHR` depending on the compiler.

Could you verify/approve/close the issue if it's also ok on your machine?

```
#include <sw/srecord.hh>
#include <cstdint>
#include <vector>
#include <string>
#include <iostream>
#include <iomanip>

int test_issue4()
{
  using namespace std;
  sw::srecord srec, srec_chk;
  std::vector<uint8_t> data;
  for(unsigned i=0; i<0xf0; ++i) data.push_back(uint8_t(i & 0xff));
  srec.set_range(0xff42, data);
  cout << srec.dump() << endl;
  stringstream ss;
  srec.compose(ss, 40);
  if(!srec_chk.parse(ss)) {
    cout << "error-msg: " << srec.error_message() << endl;
    return 1;
  }
  if(srec.dump() != srec_chk.dump()) {
    cout << "mismatch" << endl;
    return 1;
  }
  cout << "---------------------------------------------------" << endl;
  cout << srec.compose() << endl;   // -> 76 == 64 data + frame
  cout << "---------------------------------------------------" << endl;
  cout << srec.compose(10) << endl; // -> 22
  return 0;
}
```

**Comment by hansu** [comment]
Sorry, I don't agree with your new validate() method.

```c
      for(block_type& block: blocks_) {
        if(block.eadr() > 0x00ffffffu) { type = 3; break; }
        if(block.eadr() > 0x0000ffffu) { type = 2;        }
      }
```
When you leave your for-loop, `type` can not be outside the range (1..3).
And you return an error only if <1 or >3. But that will never be the case I think.
And furthermore what if block.eadr() > 0xFFFFFFFF ?

That works in my case (not testet with 16 and 24 bit addresses):
```c
      for(block_type& block: blocks_) {
        if(block.eadr() > 0x100000000ul) { type = 4; break; }
        if(block.eadr() > 0x01000000u) { type = 3; }
        if(block.eadr() > 0x00010000u) { type = 2; }
      }
```

**Comment by hansu** [comment]
And please be so kind and don't put fixes of multiple issues in one commit. That's horrible ;-)

**Comment by hansu** [comment]
You can test with this 'illegal' string `  if(!srec.parse(string("S30BFFFFFFFC0200E0FFAABBB5"))) {`
Your fix outputs:
```
ok: srec.validate()
block size: 6
block sadr: 0xfffffffc
block eadr: 0x100000002
```

**Comment by hansu** [comment]
It would also be good if the validate method is called on creation of new blocks / adding new data.
This should lead to an error but is possible now (also with my corrected validation):
```c
  srecord::block_type new_block;
  new_block.sadr(0xFFFFFFFC);
  new_block.bytes({0,1,2,3,4,5,6,7,8,9,0xa,0xb,0xc,0xd,0xe,0xf});
  srec.set_range(new_block);
```

**Comment by stfwi** [comment]
Aye, that's a good point. The class should notify if the max range is exceeded.
Gonna tackle this in the next days.
(-> Ah, for public repos I normally squash-merge into master ;) ).

**Comment by hansu** [comment]
>  (-> Ah, for public repos I normally squash-merge into master ;) ).

For public repos I would also do so, but except public issues ;-)

**Comment by hansu** [comment]
My suggestion for the validate method would also not work correctly.
Because for checking of `e_validate_record_type_to_small` we need the information of the record type which is not passed to the validate method. Either   
* we need to store the record type in the block (But the block can contain lines of different record types --> not a good idea)
* or we check for this error after parsing every line.  

I implemented the second option. See here: https://github.com/Hans470/srecord-cc/tree/validate

**Comment by stfwi** [comment]
Very cool, thanks for that. I'll dig into the matter again at the weekend. Cheers, -

**Comment by hansu** [comment]
:+1:
> 
> 
> It would also be good if the validate method is called on creation of new blocks / adding new data.
> This should lead to an error but is possible now (also with my corrected validation):
> 
> ```c
>   srecord::block_type new_block;
>   new_block.sadr(0xFFFFFFFC);
>   new_block.bytes({0,1,2,3,4,5,6,7,8,9,0xa,0xb,0xc,0xd,0xe,0xf});
>   srec.set_range(new_block);
> ```

Also a default value for the type would be good. (maybe based on. the given address)
Because if you add data to an empty srecord like here:
```c
  srecord::block_type new_block;
  new_block.sadr(0xFFFFFFFC);
  new_block.bytes({0,1,2,3,4,5,6,7,8,9});
  //srec.type(srecord::type_s3_32bit); <-- necessary
  srec.set_range(new_block);

  cout << srec << endl;
  cout << "Record type: " << srec.type() << endl;
```
this output
```
S00F0000000000000000000000000000F0
S007FFFC00010203F7
S007000004050607E2
S00500040809E5
S5030003F9
S:030000FC

Record type: 0
```
is generated.
Note the (invalid) `S0`-record for the data and the `S:`-record for the start address record.

Furthermore I think it is sufficient to test the address range on adding data (in `block_type::bytes()`) against the uint32_t range.
To test against record type would make sense in the compose-method I think.

**Comment by stfwi** [comment]
Hi, the record type should be actually set in `validate()`, so implicitly `compose()`, in the ostream operator. On my machine that works actually (quickly added type dumps and outout below). I don't see the `srec` definition in your code, could it be that it was already in error state (then `validate()` returns early to prevent overwriting that error)?

```
int test()
{
  sw::srecord srec;
  cout << "Record type: " << srec.type() << endl;
  srecord::block_type new_block;
  new_block.sadr(0xFFFFFFFC);
  new_block.bytes({0,1,2,3,4,5,6,7,8,9});
  //srec.type(srecord::type_s3_32bit); // <-- necessary?
  srec.set_range(new_block);
  cout << "Record type: " << srec.type() << endl;
  cout << srec << endl;
  cout << "Record type: " << srec.type() << endl;
  cout << "Last error: " << srec.error_message() << endl;
  return 0;
}
```

```
Record type: 0
Record type: 0
S01100000000000000000000000000000000EE
S309FFFFFFFC00010203F7
S3090000000004050607E0
S307000000040809E3
S5030003F9
S70500000000FA

Record type: 3
Last error: Ok
```

**Comment by stfwi** [comment]
Ah ok, just checked your fork. The implicit record type was moved there into the line parser, so that's not implicitly invoked anymore when composing. Should be ok to leave that check in `validate(),` `parse_line()` is private and only called in `parse()`, which does a `validate()` at the end. So also when parsing without errors the record type is set.

**Comment by stfwi** [comment]
Alright, according to the address range check I went for a early-error-return in validate(), the output of the example above is now:
```
Record type: 0
Record type: 0

Record type: 0
Last error: [validate] The data range exceeds the greatest possible address of an s-record.
```

**Comment by hansu** [comment]
>>Hi, the record type should be actually set in validate(), so implicitly compose(), in the ostream operator. On my machine that works actually (quickly added type dumps and outout below).

That works now almost. But you have to change 
`if(block.eadr() > 0xffffffffu) { return error(e_validate_record_range_exceeded); }`
to
`if(block.eadr() > 0x100000000ull) { return error(e_validate_record_range_exceeded); }`
and so on. Otherwise the last byte is not accepted.

But parsing too long (invalid) records with an record type provided are still accepted and the type is changed on compose().
The question is: Is that a wanted feature or do we want a thrown error in this case?
Or do you think thats only an academic case?  

( Otherwise, what about doing it after every line, like in my implementation?
To test with the test function of my fork:
```c
srecord srec;
int test_issue2()
{
  cout << "---------- 32 Bit too long: ----------" << endl;
  if(!srec.parse(string("S30BFFFFFFFC0200E0FFAABBB5"))) {
    cout << "error-msg: " << srec.error_message() << endl;
    cout << "error-adr: " << srec.error_address() << endl;
  } else {
      cout << srec;
  }

  cout << "---------- 32 Bit ok: ----------" << endl;
  if(!srec.parse(string("S309FFFFFFFC0200E0FF1C"))) {
    cout << "error-msg: " << srec.error_message() << endl;
    cout << "error-adr: " << srec.error_address() << endl;
  } else {
     cout << srec;
  }

  cout << "---------- 24 Bit too long: ----------" << endl;
    if(!srec.parse(string("S209FFFFFC0200E0FFAA71"))) {
       cout << "error-msg: " << srec.error_message() << endl;
       cout << "error-adr: " << srec.error_address() << endl;
     } else {
        cout << srec;
    }

  cout << "---------- 24 Bit ok: ----------" << endl;
    if(!srec.parse(string("S208FFFFFC0200E0FF1C"))) {
       cout << "error-msg: " << srec.error_message() << endl;
       cout << "error-adr: " << srec.error_address() << endl;
     } else {
        cout << srec;
    }

  cout << "---------- 16 Bit too long: ----------" << endl;
  if(!srec.parse(string("S108FFFC0200E0FFAA71"))) {
      cout << "error-msg: " << srec.error_message() << endl;
      cout << "error-adr: " << srec.error_address() << endl;
    } else {
       cout << srec;
  }

  cout << "---------- 16 Bit ok: ----------" << endl;
  if(!srec.parse(string("S107FFFC0200E0FF1C"))) {
       cout << "error-msg: " << srec.error_message() << endl;
       cout << "error-adr: " << srec.error_address() << endl;
     } else {
        cout << srec;
  }
```
)

**Comment by hansu** [comment]
And maybe checking for overlapping when adding data via .bytes() (to the same address e.g.). could be implemented.

**Comment by hansu** [comment]
And not so nice that the record type is automatically increased. If you set the record type explicit to e.g. S1 and add 24 bit data, the type will then be S2. If you set it again to S1 it will pass because it is oly checked at compose(). What do you think of adding a check in the set type function?

**Comment by stfwi** [comment]
Hi, sorry, for the late response, I can dig into the matter at the weekend. Aye, the range end value is messed up and must be definitely corrected. I am tempted to bind the auto record type setting to the `strict` flag. Up to now the feedback was that people are happy with the automatic setting. The applications (also mine in the past) were to load, merge/combine, and modify some data using setrange() - and recompose. That records were freely assembled from data was not in the application range. As this may have become more and more a thing, it may be worth to add some use case depth in that field (originally the nested block class was actually private).

**Comment by stfwi** [comment]
Oky doke, I updated the class code to fix the `eadr` regression and extended the rudimentary tests.
Alongside fixing, some functionality and convenience functionality was added (instance returning load(),
chainable merge/set_range/remove_range - stuff that I would like to have from the todays perspective).

Let's quickly check and discuss which points of the thread are still open. I add my background from
known applications here:

- 32bit address range should be ok now. It is not inclusive in the class (was confused, apps I wrote
  with that had inclusive end addreses - people can handle that better. In the class it is better
  exclusive, as c++ coders think more in `begin()` and exclusive `end()`).

- Range checks and overlap checks for editing methods: I would prefer not to add any implicit checks
  here. From a purely computer scientific view it would be absolutely correct and needed, from an
  engineering point of view, people have to know their data and memory locations. If they don't, then
  the memory image that the srecord represents is with a high probability incorrect even if no valid
  srec range is exceeded. So we most likely cannot detect incorrect ranges. The range restrictions
  are dominantly defined by the target device memory layout, not the srecord conventions.

- Overlapping blocks in combination with merging is used as a feature, where e.g. from multiple loaded
  srec files data blocks are moved into a combined production image file (aka bootloader, application,
  config, etc), where the e.g. product configuration settings overwrite the config range multiple times
  (default, default for series X, specifics). After that, CRC data are recalculated and verified, and
  finally all is recomposed to one image that is registered in the release, QM, and production repository.
  All they do there is loading the source files, verify the known values at known locations, and push
  them all into the output srec. Finally merge() and compose().

- Automatic record type setting/increasing during compose(): Is also more useful than a problem in my
  opinion. S1/S2/S3 are all the same valid and only designate the storage size of the lines. Strictly
  seen we would indeed have to raise an error. Practically, if the record exceeds the range, then there
  was already a problem before when modifying the record. So in summary people are more happy when they
  load e.g. a s19 bootloader and an s28 application, and combine that to an s28 image implicitly.
  To double check that the record type is not changed, one can call `validate(strict=true)` before
  composing.

So, it's seems to me - as with everything in the c++ world - it's a tradeoff between restricting to
a very well defined and verifying interface, and giving coders the freedom and responsibility to say
"I know what I am doing, don't make this private". Generally for embedded, the actual input data were
always the soft spot in my experience. These are the things that have to be verified very well - this
is independent of the memory representation file format, no matter if srec, ihex, zblob, etc.

Let me know what you think (if I may ask, what's your specific application for the class?),
Cheers, -

**Comment by hansu** [comment]
Thanks for reworking your code!
>In the class it is better exclusive, as c++ coders think more in begin() and exclusive end()).

Haha, yes that's a good point.

Checking for overlapping data while creating blocks I do not need actually. I only thought it could be a benefit maybe ...

And propably you are right that automatic record type setting is the best for most users ;-)

The application I needed it for was only a very simple thing. It already worked fine after adding some fixes by myself, but I think it's a great class so I wanted to have it fixed and improved for later users. 
The purpose was to generate files for firmware updates. Just to pick out a specific range of a generated srecord file, calculate a hash over this range, add some other data and output it again to a new srecord file.

**Comment by stfwi** [comment]
Perfect that. Thanks again for reaching out and the input, much appreciated!
