### ISSUE TITLE
Minimum data line length is too long

### ISSUE THREAD

**Issue by hansu** [stfwi/srecord-cc#4]
You calculate the min_data_line_length as if it is the length of the whole line, but it is used for the length of the data in the line. 
So I suggest either setting the min_data_line_length to 8 (easiest way) or use the min_data_line_length for limiting the whole line length.
```c
bool compose(std::ostream& os, size_type data_line_length=0)
  {
    if(!good() || !validate()) {
      return false;
    } else {
      size_type min_data_line_length = (2+(2*(1+type()))+8+2); // Sx+len+(adr)+((min 4 data bytes ))+cksum
     ...
```

**Comment by stfwi** [comment]
Ok, pushed a potential fix, brief test code that I used below. Could you double check with your compiler and close the issue if it is resolved for you? Cheers, - 

```
#include <sw/srecord.hh>
#include <cstdint>
#include <vector>
#include <string>
#include <iostream>
#include <iomanip>

int test_issue2()
{
  // read
  using namespace std;
  sw::srecord srec;
  if(!srec.parse(string("S309FFFFFFFC0200E0FF1C"))) {
    cout << "error-msg: " << srec.error_message() << endl;
    cout << "error-adr: " << srec.error_address() << endl;
    return 1;
  } else {
    srec.dump(cout);
  }
  // verify
  if(!srec.validate()) {
    cout << "error-msg: " << srec.error_message() << endl;
    cout << "error-adr: " << srec.error_address() << endl;
    return 1;
  } else {
    cout << "ok: srec.validate()" << endl;
  }
  // data access:
  auto& block = srec.blocks().front();
  cout << "block size: " << block.size() << endl;
  cout << "block sadr: 0x" << std::hex << block.sadr() << endl;
  cout << "block eadr: 0x" << std::hex << block.eadr() << endl;
  return 0;
}
```

**Comment by hansu** [comment]
Yes this works now but a little bit unusual to include the record field to the line size. And leads to a different behaviour when programs update to the new definition.
And you mixed up the test code for issue #2 and #4. Litte bit confusing :D.

**Comment by stfwi** [comment]
Hi, agreed, in the original old code (I once made for c++98) the line size was actually meant to be the text line size, which could be specified as max line size for embedded parsers. The c++11 porting was actually a hobby/training project - not hard to detect due to the low unit test depth ;-). I would for this purposes leave the change, it should not be critical for applications.
