### ISSUE TITLE
return type of error_address() mismatches the internal type

### ISSUE THREAD

**Issue by molokov** [stfwi/srecord-cc#5]
```
  /**
   * Returns address where validate() found an error, or 0
   * if no address is affected by an error.
   * @return address_type
   */
  inline unsigned long error_address() const
  { return error_address_; }
```

The internal member variable `error_address_` is of the `address_type` type (`unsigned long long`) but the return type here is `unsigned long` - which isn't the same type, depending on your platform. I was getting compile errors on Windows due to this.

Simplest solution is to change the return type to `address_type`

**Comment by stfwi** [comment]
Hi, thank you for the hint. Gonna fix this up quickly.
